from __future__ import annotations

from copy import deepcopy

from .contracts import BackendDescriptor, OutputLanguage, ProtocolName, TASK_IDS


PROFILE_VERSION = "2026-07-10.v3"
PRICING_SNAPSHOT = "2026-07-10.conservative-v1"

EXPECTED_LOCAL_MODEL_REVISIONS: dict[str, str] = {
    "local:voxcpm2": "bffb3df5a29440629464e5e839f4d214c8714c3d",
    "local:parakeet-tdt-0.6b-v3": "7c35754d166cca382ad1e53e68b01e7c575f3a1d",
    "local:flux.2-klein-4b": "e7b7dc27f91deacad38e78976d1f2b499d76a294",
    "local:ace-step-1.5-xl-turbo": "d4a0b288b83ebb7e25a8c0b32c573c22e134e8ee",
}


def _all_languages() -> set[OutputLanguage]:
    return {OutputLanguage.ENGLISH, OutputLanguage.FINNISH}


BACKEND_DESCRIPTORS: dict[str, BackendDescriptor] = {
    "brave:web": BackendDescriptor(
        backend_id="brave:web",
        provider="brave",
        model_id="web-search",
        revision="api-2026-07",
        protocols={ProtocolName.SEARCH},
        cloud=True,
        languages=_all_languages(),
        required_env=["BRAVE_SEARCH_API_KEY"],
        reservation_usd=0.02,
        license_name="Brave Search API terms",
    ),
    "openai:web": BackendDescriptor(
        backend_id="openai:web",
        provider="openai",
        model_id="gpt-5.6-terra",
        revision="responses-api-2026-07",
        protocols={ProtocolName.SEARCH},
        cloud=True,
        languages=_all_languages(),
        required_env=["OPENAI_API_KEY"],
        reservation_usd=0.25,
        license_name="OpenAI service terms",
    ),
    "gemini:search": BackendDescriptor(
        backend_id="gemini:search",
        provider="google",
        model_id="gemini-3.5-flash",
        revision="interactions-api-2026-07",
        protocols={ProtocolName.SEARCH},
        cloud=True,
        languages=_all_languages(),
        required_env=["GEMINI_API_KEY"],
        reservation_usd=0.20,
        license_name="Google Gemini API terms",
    ),
    "openai:gpt-5.5": BackendDescriptor(
        backend_id="openai:gpt-5.5",
        provider="openai",
        model_id="gpt-5.5",
        revision="api-alias-2026-07-10",
        protocols={ProtocolName.STRUCTURED_TEXT},
        cloud=True,
        languages=_all_languages(),
        required_env=["OPENAI_API_KEY"],
        supports_vision=True,
        reservation_usd=0.50,
        license_name="OpenAI service terms",
    ),
    "openai:gpt-5.6-terra": BackendDescriptor(
        backend_id="openai:gpt-5.6-terra",
        provider="openai",
        model_id="gpt-5.6-terra",
        revision="api-alias-2026-07-10",
        protocols={ProtocolName.STRUCTURED_TEXT},
        cloud=True,
        languages=_all_languages(),
        required_env=["OPENAI_API_KEY"],
        supports_vision=True,
        reservation_usd=0.75,
        license_name="OpenAI service terms",
        notes="Current balanced GPT-5.6 model; live Preflight confirms project access.",
    ),
    "gemini:gemini-3.5-flash": BackendDescriptor(
        backend_id="gemini:gemini-3.5-flash",
        provider="google",
        model_id="gemini-3.5-flash",
        revision="interactions-api-2026-07",
        protocols={ProtocolName.STRUCTURED_TEXT},
        cloud=True,
        languages=_all_languages(),
        required_env=["GEMINI_API_KEY"],
        supports_vision=True,
        reservation_usd=0.35,
        license_name="Google Gemini API terms",
    ),
    "local:llama-server": BackendDescriptor(
        backend_id="local:llama-server",
        provider="local",
        model_id="manifest-selected GGUF",
        revision="runner-manifest",
        protocols={ProtocolName.STRUCTURED_TEXT},
        cloud=False,
        runner="native",
        languages=_all_languages(),
        required_assets=["local-llm-profile"],
        exclusive_gpu=True,
        license_name="model-specific; frozen in runner manifest",
        notes="Uses one manifest-selected GGUF through a pinned stock Windows llama-server process.",
    ),
    "local:qwen3.6-27b-q4-vision": BackendDescriptor(
        backend_id="local:qwen3.6-27b-q4-vision",
        provider="local",
        model_id="Qwen/Qwen3.6-27B-vision",
        revision="evaluation-gated",
        protocols={ProtocolName.STRUCTURED_TEXT},
        cloud=False,
        runner="either",
        languages=_all_languages(),
        required_assets=["qwen3.6-27b-q4-vision"],
        supports_vision=True,
        exclusive_gpu=True,
        license_name="Apache-2.0",
        notes="Final-quality local use is blocked until this runner passes its memory/vision probe.",
    ),
    "elevenlabs:eleven_multilingual_v2": BackendDescriptor(
        backend_id="elevenlabs:eleven_multilingual_v2",
        provider="elevenlabs",
        model_id="eleven_multilingual_v2",
        revision="api-2026-07",
        protocols={ProtocolName.SPEECH},
        cloud=True,
        languages=_all_languages(),
        required_env=["ELEVENLABS_API_KEY"],
        supports_word_timing=True,
        supports_voice_cloning=True,
        reservation_usd=0.30,
        license_name="ElevenLabs service terms",
    ),
    "elevenlabs:forced-alignment": BackendDescriptor(
        backend_id="elevenlabs:forced-alignment",
        provider="elevenlabs",
        model_id="forced-alignment",
        revision="api-2026-07",
        protocols={ProtocolName.ALIGNMENT},
        cloud=True,
        languages=_all_languages(),
        required_env=["ELEVENLABS_API_KEY"],
        reservation_usd=0.20,
        license_name="ElevenLabs service terms",
        notes="Normally skipped because ElevenLabs TTS returns character timing.",
    ),
    "local:voxcpm2": BackendDescriptor(
        backend_id="local:voxcpm2",
        provider="local",
        model_id="openbmb/VoxCPM2",
        revision="runner-manifest-v1",
        protocols={ProtocolName.SPEECH},
        cloud=False,
        runner="native",
        languages=_all_languages(),
        required_assets=["voxcpm2"],
        supports_voice_cloning=True,
        exclusive_gpu=True,
        license_name="Apache-2.0",
    ),
    "local:parakeet-tdt-0.6b-v3": BackendDescriptor(
        backend_id="local:parakeet-tdt-0.6b-v3",
        provider="local",
        model_id="nvidia/parakeet-tdt-0.6b-v3",
        revision="runner-manifest-v1",
        protocols={ProtocolName.ALIGNMENT},
        cloud=False,
        runner="wsl",
        languages=_all_languages(),
        required_assets=["parakeet-tdt-0.6b-v3"],
        exclusive_gpu=True,
        license_name="CC-BY-4.0",
    ),
    "openai:gpt-image-2": BackendDescriptor(
        backend_id="openai:gpt-image-2",
        provider="openai",
        model_id="gpt-image-2",
        revision="gpt-image-2-2026-04-21",
        protocols={ProtocolName.IMAGE},
        cloud=True,
        languages=_all_languages(),
        required_env=["OPENAI_API_KEY"],
        supports_reference_images=True,
        reservation_usd=0.30,
        license_name="OpenAI service terms",
    ),
    "gemini:gemini-3.1-flash-image": BackendDescriptor(
        backend_id="gemini:gemini-3.1-flash-image",
        provider="google",
        model_id="gemini-3.1-flash-image",
        revision="interactions-api-2026-07",
        protocols={ProtocolName.IMAGE},
        cloud=True,
        languages=_all_languages(),
        required_env=["GEMINI_API_KEY"],
        supports_reference_images=True,
        reservation_usd=0.25,
        license_name="Google Gemini API terms",
    ),
    "local:flux.2-klein-4b": BackendDescriptor(
        backend_id="local:flux.2-klein-4b",
        provider="local",
        model_id="black-forest-labs/FLUX.2-klein-4B",
        revision="runner-manifest-v1",
        protocols={ProtocolName.IMAGE},
        cloud=False,
        runner="native",
        languages=_all_languages(),
        required_assets=["flux.2-klein-4b"],
        supports_reference_images=True,
        exclusive_gpu=True,
        license_name="Apache-2.0",
    ),
    "elevenlabs:music_v2": BackendDescriptor(
        backend_id="elevenlabs:music_v2",
        provider="elevenlabs",
        model_id="music_v2",
        revision="api-2026-07",
        protocols={ProtocolName.MUSIC},
        cloud=True,
        languages=_all_languages(),
        required_env=["ELEVENLABS_API_KEY"],
        max_duration_seconds=600,
        supports_looping=True,
        reservation_usd=1.50,
        license_name="ElevenLabs service terms",
        notes="Generation is capped at 600 seconds; longer timelines require an explicitly seamless loop.",
    ),
    "local:ace-step-1.5-xl-turbo": BackendDescriptor(
        backend_id="local:ace-step-1.5-xl-turbo",
        provider="local",
        model_id="ACE-Step/acestep-v15-xl-turbo",
        revision="runner-manifest-v1",
        protocols={ProtocolName.MUSIC},
        cloud=False,
        runner="native",
        languages=_all_languages(),
        required_assets=["ace-step-1.5-xl-turbo"],
        max_duration_seconds=600,
        supports_looping=True,
        exclusive_gpu=True,
        license_name="MIT",
    ),
    "deterministic:structured": BackendDescriptor(
        backend_id="deterministic:structured",
        provider="deterministic",
        model_id="fixture-v1",
        revision="1",
        protocols={ProtocolName.STRUCTURED_TEXT},
        cloud=False,
        languages=_all_languages(),
        license_name="Apache-2.0",
        notes="Test/evaluation fixture only; never a silent production fallback.",
    ),
    "deterministic:search": BackendDescriptor(
        backend_id="deterministic:search",
        provider="deterministic",
        model_id="fixture-v1",
        revision="1",
        protocols={ProtocolName.SEARCH},
        cloud=False,
        languages=_all_languages(),
        license_name="Apache-2.0",
        notes="Test/evaluation fixture only.",
    ),
    "deterministic:speech": BackendDescriptor(
        backend_id="deterministic:speech",
        provider="deterministic",
        model_id="fixture-v1",
        revision="1",
        protocols={ProtocolName.SPEECH},
        cloud=False,
        languages=_all_languages(),
        supports_word_timing=True,
        license_name="Apache-2.0",
    ),
    "deterministic:alignment": BackendDescriptor(
        backend_id="deterministic:alignment",
        provider="deterministic",
        model_id="fixture-v1",
        revision="1",
        protocols={ProtocolName.ALIGNMENT},
        cloud=False,
        languages=_all_languages(),
        license_name="Apache-2.0",
    ),
    "deterministic:stick": BackendDescriptor(
        backend_id="deterministic:stick",
        provider="deterministic",
        model_id="stick-raster-v1",
        revision="1",
        protocols={ProtocolName.IMAGE},
        cloud=False,
        languages=_all_languages(),
        license_name="Apache-2.0",
        notes="Explicit test/manual Backend, never an automatic image fallback.",
    ),
    "deterministic:music": BackendDescriptor(
        backend_id="deterministic:music",
        provider="deterministic",
        model_id="fixture-v1",
        revision="1",
        protocols={ProtocolName.MUSIC},
        cloud=False,
        languages=_all_languages(),
        license_name="Apache-2.0",
    ),
}


def _text_tasks(backend_id: str) -> dict[str, str]:
    return {
        task_id: backend_id
        for task_id in TASK_IDS
        if task_id
        in {
            "research",
            "ideate",
            "select",
            "outline",
            "script_draft",
            "review_story",
            "review_spoken",
            "review_constraints",
            "script_revision",
            "factual_review",
            "duration_repair",
            "visual_plan",
            "image_prompt_compile",
            "music_brief",
        }
    }


def _profile(
    *,
    search: str,
    text: str,
    speech: str,
    alignment: str,
    image: str,
    review: str,
    music: str,
) -> dict[str, str]:
    result = _text_tasks(text)
    result.update(
        {
            "search": search,
            "narration_synthesis": speech,
            "caption_alignment": alignment,
            "image_generate": image,
            "visual_review": review,
            "music_generate": music,
        }
    )
    assert set(result) == set(TASK_IDS)
    return result


PROFILES: dict[str, dict[str, str]] = {
    "local": _profile(
        search="brave:web",
        text="local:llama-server",
        speech="local:voxcpm2",
        alignment="local:parakeet-tdt-0.6b-v3",
        image="local:flux.2-klein-4b",
        review="local:qwen3.6-27b-q4-vision",
        music="local:ace-step-1.5-xl-turbo",
    ),
    "cloud-openai": _profile(
        search="openai:web",
        text="openai:gpt-5.6-terra",
        speech="elevenlabs:eleven_multilingual_v2",
        alignment="elevenlabs:forced-alignment",
        image="openai:gpt-image-2",
        review="openai:gpt-5.6-terra",
        music="elevenlabs:music_v2",
    ),
    "cloud-gemini": _profile(
        search="gemini:search",
        text="gemini:gemini-3.5-flash",
        speech="elevenlabs:eleven_multilingual_v2",
        alignment="elevenlabs:forced-alignment",
        image="gemini:gemini-3.1-flash-image",
        review="gemini:gemini-3.5-flash",
        music="elevenlabs:music_v2",
    ),
    "hybrid-local-first": _profile(
        search="brave:web",
        text="local:llama-server",
        speech="elevenlabs:eleven_multilingual_v2",
        alignment="elevenlabs:forced-alignment",
        image="local:flux.2-klein-4b",
        review="local:qwen3.6-27b-q4-vision",
        music="local:ace-step-1.5-xl-turbo",
    ),
    "deterministic-test": _profile(
        search="deterministic:search",
        text="deterministic:structured",
        speech="deterministic:speech",
        alignment="deterministic:alignment",
        image="deterministic:stick",
        review="deterministic:structured",
        music="deterministic:music",
    ),
}


def resolve_profile(name: str) -> dict[str, str]:
    try:
        return deepcopy(PROFILES[name])
    except KeyError as exc:
        raise KeyError(f"unknown Run Profile: {name}") from exc
