from __future__ import annotations

from copy import deepcopy

from .contracts import BackendDescriptor, OutputLanguage, ProtocolName, TASK_IDS
from .costs import PRICING_SNAPSHOT


PROFILE_VERSION = "2026-07-16.v11"

EXPECTED_LOCAL_MODEL_REVISIONS: dict[str, str] = {
    "local:voxcpm2": "bffb3df5a29440629464e5e839f4d214c8714c3d",
    "local:faster-whisper-large-v3-turbo": "0a363e9161cbc7ed1431c9597a8ceaf0c4f78fcf",
    "local:parakeet-tdt-0.6b-v3": "7c35754d166cca382ad1e53e68b01e7c575f3a1d",
    "local:flux.2-klein-4b": "e7b7dc27f91deacad38e78976d1f2b499d76a294",
    "local:omnivoice": "c5fdb5ccb189668d56333f77ba2629f4cd7535f4",
    "local:moss-tts-v1.5": "be7766a6735b98bd793f7c79fb720b4d0f5d13b8",
    "local:x-voice": "7f24fe778ddf7a47e25d87e5d5153599c1d4d5c2",
    "local:higgs-tts-3-4b": "7556c17e05201fccd9c8cc120bc216dcc7b5d561",
    "local:z-image-turbo": "f332072aa78be7aecdf3ee76d5c247082da564a6",
    "local:ideogram-4-nf4": "1874bc70267ba2c823a7239e1d70dd308c8d64dc",
    "local:qwen-image-2512-nf4": "25468b98e3276ca6700de15c6628e51b7de54a26",
    "local:ace-step-1.5-xl-turbo": "d4a0b288b83ebb7e25a8c0b32c573c22e134e8ee",
}


def image_generation_dimensions(
    backend_id: str,
    *,
    delivery_width: int,
    delivery_height: int,
) -> tuple[int, int]:
    if backend_id in {
        "local:flux.2-klein-4b",
        "local:z-image-turbo",
        "local:ideogram-4-nf4",
        "local:qwen-image-2512-nf4",
    }:
        return 1024, 576
    if backend_id == "deterministic:stick":
        return delivery_width, delivery_height
    return 2048, 1152


def _all_languages() -> set[OutputLanguage]:
    return {OutputLanguage.ENGLISH, OutputLanguage.FINNISH}


BACKEND_DESCRIPTORS: dict[str, BackendDescriptor] = {
    "brave:web": BackendDescriptor(
        backend_id="brave:web",
        provider="brave",
        model_id="web-search",
        revision="api-2026-07",
        protocols={ProtocolName.SEARCH},
        cloud=True,
        languages=_all_languages(),
        required_env=["BRAVE_SEARCH_API_KEY"],
        reservation_usd=0.02,
        license_name="Brave Search API terms",
    ),
    "ddgs:duckduckgo": BackendDescriptor(
        backend_id="ddgs:duckduckgo",
        provider="ddgs",
        model_id="duckduckgo-text",
        revision="ddgs-9.14.4-keyless-fallback-v4",
        protocols={ProtocolName.SEARCH},
        cloud=True,
        languages=_all_languages(),
        license_name="MIT",
        notes=(
            "Keyless bounded DDGS search with DuckDuckGo first, DDGS keyless fallbacks, then a "
            "fixed-host MediaWiki search fallback with bounded relevant page excerpts; no "
            "arbitrary-host extraction."
        ),
    ),
    "openai:web": BackendDescriptor(
        backend_id="openai:web",
        provider="openai",
        model_id="gpt-5.6-terra",
        revision="responses-api-2026-07-required-search-tool",
        protocols={ProtocolName.SEARCH},
        cloud=True,
        languages=_all_languages(),
        required_env=["OPENAI_API_KEY"],
        reservation_usd=0.25,
        license_name="OpenAI service terms",
    ),
    "gemini:search": BackendDescriptor(
        backend_id="gemini:search",
        provider="google",
        model_id="gemini-3.5-flash",
        revision="interactions-api-2026-07-any-search-tool",
        protocols={ProtocolName.SEARCH},
        cloud=True,
        languages=_all_languages(),
        required_env=["GEMINI_API_KEY"],
        reservation_usd=0.20,
        license_name="Google Gemini API terms",
    ),
    "openai:gpt-5.5": BackendDescriptor(
        backend_id="openai:gpt-5.5",
        provider="openai",
        model_id="gpt-5.5",
        revision="api-alias-2026-07-10",
        protocols={ProtocolName.STRUCTURED_TEXT},
        cloud=True,
        languages=_all_languages(),
        required_env=["OPENAI_API_KEY"],
        supports_vision=True,
        reservation_usd=0.50,
        license_name="OpenAI service terms",
    ),
    "openai:gpt-5.4-mini": BackendDescriptor(
        backend_id="openai:gpt-5.4-mini",
        provider="openai",
        model_id="gpt-5.4-mini-2026-03-17",
        revision="gpt-5.4-mini-2026-03-17",
        protocols={ProtocolName.STRUCTURED_TEXT},
        cloud=True,
        languages=_all_languages(),
        required_env=["OPENAI_API_KEY"],
        supports_vision=True,
        reservation_usd=0.25,
        license_name="OpenAI service terms",
        notes="Pinned cost-efficient GPT-5.4 mini snapshot for structured production tasks.",
    ),
    "openai:gpt-5.6-terra": BackendDescriptor(
        backend_id="openai:gpt-5.6-terra",
        provider="openai",
        model_id="gpt-5.6-terra",
        revision="api-alias-2026-07-10",
        protocols={ProtocolName.STRUCTURED_TEXT},
        cloud=True,
        languages=_all_languages(),
        required_env=["OPENAI_API_KEY"],
        supports_vision=True,
        reservation_usd=0.75,
        license_name="OpenAI service terms",
        notes="Current balanced GPT-5.6 model; live Preflight confirms project access.",
    ),
    "gemini:gemini-3.5-flash": BackendDescriptor(
        backend_id="gemini:gemini-3.5-flash",
        provider="google",
        model_id="gemini-3.5-flash",
        revision="interactions-api-2026-07",
        protocols={ProtocolName.STRUCTURED_TEXT},
        cloud=True,
        languages=_all_languages(),
        required_env=["GEMINI_API_KEY"],
        supports_vision=True,
        reservation_usd=0.35,
        license_name="Google Gemini API terms",
    ),
    "local:llama-server": BackendDescriptor(
        backend_id="local:llama-server",
        provider="local",
        model_id="manifest-selected GGUF",
        revision="runner-manifest",
        protocols={ProtocolName.STRUCTURED_TEXT},
        cloud=False,
        runner="native",
        languages=_all_languages(),
        required_assets=["local-llm-profile"],
        exclusive_gpu=True,
        license_name="model-specific; frozen in runner manifest",
        notes="Uses one manifest-selected GGUF through a pinned stock Windows llama-server process.",
    ),
    "local:qwen3.6-27b-q4-vision": BackendDescriptor(
        backend_id="local:qwen3.6-27b-q4-vision",
        provider="local",
        model_id="Qwen/Qwen3.6-27B-vision",
        revision="evaluation-gated",
        protocols={ProtocolName.STRUCTURED_TEXT},
        cloud=False,
        runner="either",
        languages=_all_languages(),
        required_assets=["qwen3.6-27b-q4-vision"],
        supports_vision=True,
        exclusive_gpu=True,
        license_name="Apache-2.0",
        notes="Final-quality local use is blocked until this runner passes its memory/vision probe.",
    ),
    "elevenlabs:eleven_multilingual_v2": BackendDescriptor(
        backend_id="elevenlabs:eleven_multilingual_v2",
        provider="elevenlabs",
        model_id="eleven_multilingual_v2",
        revision="api-2026-07",
        protocols={ProtocolName.SPEECH},
        cloud=True,
        languages=_all_languages(),
        required_env=["ELEVENLABS_API_KEY"],
        supports_word_timing=True,
        supports_voice_cloning=True,
        reservation_usd=0.30,
        license_name="ElevenLabs service terms",
    ),
    "elevenlabs:forced-alignment": BackendDescriptor(
        backend_id="elevenlabs:forced-alignment",
        provider="elevenlabs",
        model_id="forced-alignment",
        revision="api-2026-07",
        protocols={ProtocolName.ALIGNMENT},
        cloud=True,
        languages=_all_languages(),
        required_env=["ELEVENLABS_API_KEY"],
        reservation_usd=0.20,
        license_name="ElevenLabs service terms",
        notes="Normally skipped because ElevenLabs TTS returns character timing.",
    ),
    "local:voxcpm2": BackendDescriptor(
        backend_id="local:voxcpm2",
        provider="local",
        model_id="openbmb/VoxCPM2",
        revision="runner-manifest-v1",
        protocols={ProtocolName.SPEECH},
        cloud=False,
        runner="native",
        languages=_all_languages(),
        required_assets=["voxcpm2"],
        supports_voice_cloning=True,
        exclusive_gpu=True,
        license_name="Apache-2.0",
    ),
    "local:omnivoice": BackendDescriptor(
        backend_id="local:omnivoice",
        provider="local",
        model_id="k2-fsa/OmniVoice",
        revision="runner-manifest-v1",
        protocols={ProtocolName.SPEECH},
        cloud=False,
        runner="native",
        languages=_all_languages(),
        required_assets=["omnivoice"],
        supports_voice_cloning=True,
        requires_reference_transcript=True,
        exclusive_gpu=True,
        license_name="CC-BY-NC-4.0",
        notes="Native Windows challenger; authorized 3–10 second voice references are recommended.",
    ),
    "local:moss-tts-v1.5": BackendDescriptor(
        backend_id="local:moss-tts-v1.5",
        provider="local",
        model_id="OpenMOSS-Team/MOSS-TTS-Local-Transformer-v1.5",
        revision="runner-manifest-v1",
        protocols={ProtocolName.SPEECH},
        cloud=False,
        runner="native",
        languages=_all_languages(),
        required_assets=["moss-tts-v1.5", "moss-audio-tokenizer-v2"],
        supports_voice_cloning=True,
        exclusive_gpu=True,
        license_name="Apache-2.0",
        notes="Native Windows challenger using pinned local remote code and SDPA; requires a fit probe.",
    ),
    "local:x-voice": BackendDescriptor(
        backend_id="local:x-voice",
        provider="local",
        model_id="XRXRX/X-Voice Stage1",
        revision="runner-manifest-v1",
        protocols={ProtocolName.SPEECH},
        cloud=False,
        runner="native",
        languages=_all_languages(),
        required_assets=["x-voice-stage1", "vocos-mel-24khz", "espeak-ng"],
        supports_voice_cloning=True,
        requires_reference_transcript=True,
        requires_reference_language=True,
        exclusive_gpu=True,
        license_name="CC-BY-NC-4.0",
        notes=(
            "Experimental native-Windows Stage1 backend with a pinned Conda/Pynini runtime; "
            "the model weights prohibit commercial use."
        ),
    ),
    "local:higgs-tts-3-4b": BackendDescriptor(
        backend_id="local:higgs-tts-3-4b",
        provider="local",
        model_id="bosonai/higgs-tts-3-4b",
        revision="runner-manifest-v1",
        protocols={ProtocolName.SPEECH},
        cloud=False,
        runner="docker",
        languages=_all_languages(),
        required_assets=["higgs-tts-3-4b", "sglang-omni-docker"],
        supports_voice_cloning=True,
        requires_reference_transcript=True,
        exclusive_gpu=True,
        license_name="Boson AI Higgs Audio Research License + Creator Use Grant",
        notes=(
            "Docker Desktop/WSL2 challenger with allowlisted delivery controls. Published creator "
            "works require prominent Boson AI attribution; hosting or product embedding requires "
            "a separate commercial license."
        ),
    ),
    "local:parakeet-tdt-0.6b-v3": BackendDescriptor(
        backend_id="local:parakeet-tdt-0.6b-v3",
        provider="local",
        model_id="nvidia/parakeet-tdt-0.6b-v3",
        revision="runner-manifest-v1",
        protocols={ProtocolName.ALIGNMENT},
        cloud=False,
        runner="wsl",
        languages=_all_languages(),
        required_assets=["parakeet-tdt-0.6b-v3"],
        exclusive_gpu=True,
        license_name="CC-BY-4.0",
    ),
    "local:faster-whisper-large-v3-turbo": BackendDescriptor(
        backend_id="local:faster-whisper-large-v3-turbo",
        provider="local",
        model_id="dropbox-dash/faster-whisper-large-v3-turbo",
        revision="runner-manifest-v1",
        protocols={ProtocolName.ALIGNMENT},
        cloud=False,
        runner="native",
        languages=_all_languages(),
        required_assets=["faster-whisper-large-v3-turbo"],
        exclusive_gpu=True,
        license_name="MIT",
        notes="Native Windows word timestamps; canonical captions still come from exact-script reconciliation.",
    ),
    "openai:gpt-image-2": BackendDescriptor(
        backend_id="openai:gpt-image-2",
        provider="openai",
        model_id="gpt-image-2",
        revision="gpt-image-2-2026-04-21",
        protocols={ProtocolName.IMAGE},
        cloud=True,
        languages=_all_languages(),
        required_env=["OPENAI_API_KEY"],
        supports_reference_images=True,
        reservation_usd=0.30,
        license_name="OpenAI service terms",
    ),
    "gemini:gemini-3.1-flash-image": BackendDescriptor(
        backend_id="gemini:gemini-3.1-flash-image",
        provider="google",
        model_id="gemini-3.1-flash-image",
        revision="interactions-api-2026-07",
        protocols={ProtocolName.IMAGE},
        cloud=True,
        languages=_all_languages(),
        required_env=["GEMINI_API_KEY"],
        supports_reference_images=True,
        reservation_usd=0.25,
        license_name="Google Gemini API terms",
    ),
    "local:flux.2-klein-4b": BackendDescriptor(
        backend_id="local:flux.2-klein-4b",
        provider="local",
        model_id="black-forest-labs/FLUX.2-klein-4B",
        revision="runner-manifest-v1",
        protocols={ProtocolName.IMAGE},
        cloud=False,
        runner="native",
        languages=_all_languages(),
        required_assets=["flux.2-klein-4b"],
        supports_reference_images=True,
        supports_negative_prompt=True,
        exclusive_gpu=True,
        license_name="Apache-2.0",
        notes="Negative exclusions are folded into the positive prompt at this low-guidance setting.",
    ),
    "local:z-image-turbo": BackendDescriptor(
        backend_id="local:z-image-turbo",
        provider="local",
        model_id="Tongyi-MAI/Z-Image-Turbo",
        revision="runner-manifest-v1",
        protocols={ProtocolName.IMAGE},
        cloud=False,
        runner="native",
        languages=_all_languages(),
        required_assets=["z-image-turbo"],
        supports_negative_prompt=True,
        exclusive_gpu=True,
        license_name="Apache-2.0",
        notes="Text-to-image only; Turbo guidance is zero, so exclusions are compiled into the positive prompt.",
    ),
    "local:ideogram-4-nf4": BackendDescriptor(
        backend_id="local:ideogram-4-nf4",
        provider="local",
        model_id="ideogram-ai/ideogram-4-nf4-diffusers",
        revision="runner-manifest-v1",
        protocols={ProtocolName.IMAGE},
        cloud=False,
        runner="native",
        languages=_all_languages(),
        required_assets=["ideogram-4-nf4"],
        supports_negative_prompt=True,
        exclusive_gpu=True,
        license_name="Ideogram 4 Non-Commercial",
        notes="Gated text-to-image challenger; Python compiles the existing prompt into native JSON locally.",
    ),
    "local:qwen-image-2512-nf4": BackendDescriptor(
        backend_id="local:qwen-image-2512-nf4",
        provider="local",
        model_id="Qwen/Qwen-Image-2512",
        revision="runner-manifest-v1",
        protocols={ProtocolName.IMAGE},
        cloud=False,
        runner="native",
        languages=_all_languages(),
        required_assets=["qwen-image-2512"],
        supports_negative_prompt=True,
        exclusive_gpu=True,
        license_name="Apache-2.0",
        notes="Text-to-image only; transformer and text encoder load as NF4 with model CPU offload.",
    ),
    "elevenlabs:music_v2": BackendDescriptor(
        backend_id="elevenlabs:music_v2",
        provider="elevenlabs",
        model_id="music_v2",
        revision="api-2026-07",
        protocols={ProtocolName.MUSIC},
        cloud=True,
        languages=_all_languages(),
        required_env=["ELEVENLABS_API_KEY"],
        max_duration_seconds=600,
        supports_looping=True,
        reservation_usd=1.50,
        license_name="ElevenLabs service terms",
        notes="Generation is capped at 600 seconds; longer timelines require an explicitly seamless loop.",
    ),
    "local:ace-step-1.5-xl-turbo": BackendDescriptor(
        backend_id="local:ace-step-1.5-xl-turbo",
        provider="local",
        model_id="ACE-Step/acestep-v15-xl-turbo",
        revision="runner-manifest-v1",
        protocols={ProtocolName.MUSIC},
        cloud=False,
        runner="native",
        languages=_all_languages(),
        required_assets=["ace-step-1.5-xl-turbo"],
        max_duration_seconds=600,
        supports_looping=True,
        exclusive_gpu=True,
        license_name="MIT",
    ),
    "deterministic:structured": BackendDescriptor(
        backend_id="deterministic:structured",
        provider="deterministic",
        model_id="fixture-v1",
        revision="1",
        protocols={ProtocolName.STRUCTURED_TEXT},
        cloud=False,
        languages=_all_languages(),
        license_name="Apache-2.0",
        notes="Test/evaluation fixture only; never a silent production fallback.",
    ),
    "deterministic:search": BackendDescriptor(
        backend_id="deterministic:search",
        provider="deterministic",
        model_id="fixture-v1",
        revision="1",
        protocols={ProtocolName.SEARCH},
        cloud=False,
        languages=_all_languages(),
        license_name="Apache-2.0",
        notes="Test/evaluation fixture only.",
    ),
    "deterministic:speech": BackendDescriptor(
        backend_id="deterministic:speech",
        provider="deterministic",
        model_id="fixture-v1",
        revision="1",
        protocols={ProtocolName.SPEECH},
        cloud=False,
        languages=_all_languages(),
        supports_word_timing=True,
        license_name="Apache-2.0",
    ),
    "deterministic:alignment": BackendDescriptor(
        backend_id="deterministic:alignment",
        provider="deterministic",
        model_id="fixture-v1",
        revision="1",
        protocols={ProtocolName.ALIGNMENT},
        cloud=False,
        languages=_all_languages(),
        license_name="Apache-2.0",
    ),
    "deterministic:stick": BackendDescriptor(
        backend_id="deterministic:stick",
        provider="deterministic",
        model_id="stick-raster-v1",
        revision="1",
        protocols={ProtocolName.IMAGE},
        cloud=False,
        languages=_all_languages(),
        license_name="Apache-2.0",
        notes="Explicit test/manual Backend, never an automatic image fallback.",
    ),
    "deterministic:music": BackendDescriptor(
        backend_id="deterministic:music",
        provider="deterministic",
        model_id="fixture-v1",
        revision="1",
        protocols={ProtocolName.MUSIC},
        cloud=False,
        languages=_all_languages(),
        license_name="Apache-2.0",
    ),
}


def _text_tasks(backend_id: str) -> dict[str, str]:
    return {
        task_id: backend_id
        for task_id in TASK_IDS
        if task_id
        in {
            "research",
            "ideate",
            "select",
            "outline",
            "script_draft",
            "review_story",
            "review_spoken",
            "review_constraints",
            "script_revision",
            "claim_inventory",
            "factual_review",
            "duration_repair",
            "visual_plan",
            "remotion_direction",
            "remotion_asset_select",
            "image_prompt_compile",
            "music_brief",
        }
    }


def _profile(
    *,
    search: str,
    text: str,
    speech: str,
    alignment: str,
    image: str,
    review: str,
    music: str,
) -> dict[str, str]:
    result = _text_tasks(text)
    result.update(
        {
            "search": search,
            "narration_synthesis": speech,
            "caption_alignment": alignment,
            "image_generate": image,
            "visual_review": review,
            "music_generate": music,
        }
    )
    assert set(result) == set(TASK_IDS)
    return result


PROFILES: dict[str, dict[str, str]] = {
    "local": _profile(
        search="ddgs:duckduckgo",
        text="local:llama-server",
        speech="local:voxcpm2",
        alignment="local:faster-whisper-large-v3-turbo",
        image="local:flux.2-klein-4b",
        review="local:qwen3.6-27b-q4-vision",
        music="local:ace-step-1.5-xl-turbo",
    ),
    "cloud-openai": _profile(
        search="openai:web",
        text="openai:gpt-5.6-terra",
        speech="elevenlabs:eleven_multilingual_v2",
        alignment="elevenlabs:forced-alignment",
        image="openai:gpt-image-2",
        review="openai:gpt-5.6-terra",
        music="elevenlabs:music_v2",
    ),
    "cloud-gemini": _profile(
        search="gemini:search",
        text="gemini:gemini-3.5-flash",
        speech="elevenlabs:eleven_multilingual_v2",
        alignment="elevenlabs:forced-alignment",
        image="gemini:gemini-3.1-flash-image",
        review="gemini:gemini-3.5-flash",
        music="elevenlabs:music_v2",
    ),
    "cloud-openai-gemini": _profile(
        search="ddgs:duckduckgo",
        text="openai:gpt-5.4-mini",
        speech="elevenlabs:eleven_multilingual_v2",
        alignment="elevenlabs:forced-alignment",
        image="gemini:gemini-3.1-flash-image",
        review="openai:gpt-5.4-mini",
        music="elevenlabs:music_v2",
    ),
    "hybrid-local-first": _profile(
        search="ddgs:duckduckgo",
        text="local:llama-server",
        speech="elevenlabs:eleven_multilingual_v2",
        alignment="elevenlabs:forced-alignment",
        image="local:flux.2-klein-4b",
        review="local:qwen3.6-27b-q4-vision",
        music="local:ace-step-1.5-xl-turbo",
    ),
    "deterministic-test": _profile(
        search="deterministic:search",
        text="deterministic:structured",
        speech="deterministic:speech",
        alignment="deterministic:alignment",
        image="deterministic:stick",
        review="deterministic:structured",
        music="deterministic:music",
    ),
}


def resolve_profile(name: str) -> dict[str, str]:
    try:
        return deepcopy(PROFILES[name])
    except KeyError as exc:
        raise KeyError(f"unknown Run Profile: {name}") from exc
